name: sample_chat_app
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  socket_io_client: ^2.0.0
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  
  
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.0
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

flutter_intl:
  main_locale: en_US
  enabled: true